### ISSUE TITLE
Can't build on x64

### ISSUE THREAD

**Issue by Chadster766** [gnab/rtl8812au#16]
My development platform is Debian x64 and I would like to build this x64.

**Comment by refecuti** [comment]
looked very promising at first but nope, looking forward to solutions

root@kali:~/Downloads/rtl8812au-master# sudo make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/3.18.0-kali3-amd64/build M=/root/Downloads/rtl8812au-master  modules
make[1]: Entering directory `/usr/src/linux-headers-3.18.0-kali3-amd64'
  CC [M]  /root/Downloads/rtl8812au-master/core/rtw_cmd.o
  CC [M]  /root/Downloads/rtl8812au-master/core/rtw_security.o
  CC [M]  /root/Downloads/rtl8812au-master/core/rtw_debug.o
  CC [M]  /root/Downloads/rtl8812au-master/core/rtw_io.o
  CC [M]  /root/Downloads/rtl8812au-master/core/rtw_ioctl_query.o
  CC [M]  /root/Downloads/rtl8812au-master/core/rtw_ioctl_set.o
  CC [M]  /root/Downloads/rtl8812au-master/core/rtw_ieee80211.o
  CC [M]  /root/Downloads/rtl8812au-master/core/rtw_mlme.o
  CC [M]  /root/Downloads/rtl8812au-master/core/rtw_mlme_ext.o
/root/Downloads/rtl8812au-master/core/rtw_mlme_ext.c: In function 'OnProbeReq':
/root/Downloads/rtl8812au-master/core/rtw_mlme_ext.c:833:15: error: 'struct rx_pkt_attrib' has no member named 'mcs_rate'
make[4]: *** [/root/Downloads/rtl8812au-master/core/rtw_mlme_ext.o] Error 1
make[3]: *** [_module_/root/Downloads/rtl8812au-master] Error 2
make[2]: *** [sub-make] Error 2
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.18.0-kali3-amd64'
make: *** [modules] Error 2

**Comment by refecuti** [comment]
looked promising at first... looking for solutions too

![screenshot from 2015-06-12 19 26 36](https://cloud.githubusercontent.com/assets/12867115/8141703/7acb5d6e-115a-11e5-8eb1-28693ddecf8c.png)

**Comment by refecuti** [comment]
Hey, whats going on here ?

""root@kali:~/Downloads/rtl8812au-master# make
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/3.18.0-kali3-amd64/build M=/root/Downloads/rtl8812au-master  modules
make[1]: Entering directory `/usr/src/linux-headers-3.18.0-kali3-amd64'
make[4]: *** No rule to make target `/root/Downloads/rtl8812au-master/os_dep/linux/pci_intf.o', needed by `/root/Downloads/rtl8812au-master/8812ae.o'.  Stop.
make[3]: *** [_module_/root/Downloads/rtl8812au-master] Error 2
make[2]: *** [sub-make] Error 2
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-3.18.0-kali3-amd64'
make: *** [modules] Error 2 ""


"" linux-headers-3.18.0-kali3-all is already the newest version.
linux-headers-3.18.0-kali3-all-amd64 is already the newest version.
linux-headers-3.18.0-kali3-amd64 is already the newest version.
linux-headers-3.18.0-kali3-common is already the newest version.
linux-headers-amd64 is already the newest version. ""

**Comment by Chadster766** [comment]
Great Job!

This time I ran the below commands and it work straight out for my Debian x64 machine:

```
make
make install
```
