### ISSUE TITLE
LED constantly blinking

### ISSUE THREAD

**Issue by severidaniele** [gnab/rtl8812au#18]
Hi, apologies if this is not the right place to ask but is there a way to change the LED behavior?

I have compiled the driver to be used on a Raspberry Pi with an Edimax EW-7811UTC
AC600 Wireless Dual-Band Mini USB Adapter. It works fine, but the LED is constantly blinking, even when there is no network activity.
I don't know if this is the normal expected behavior but this is particularly annoying in a dark room (e.g. when sleeping at night).

Is there a way to change the source code to change the LED blinking behavior or eventually to turn it off?

I have had a look at the files in the repository (in particular the ones which seems related to the LED) but I lack programming skills and I could not figure out what eventually I should change.

Thank you.

**Comment by nbartos** [comment]
This change adds the option to turn off the LED at runtime:  https://github.com/gnab/rtl8812au/pull/102
