### ISSUE TITLE
error when run "make dkms_install"

### ISSUE THREAD

**Issue by mengzonefire** [gnab/rtl8812au#208]
in Makefile:
DRIVER_VERSION = $(shell grep "#define DRIVERVERSION" include/rtw_version.h | awk '{print $$3}' | tr -d v\\")
need to replace by
DRIVER_VERSION = $(shell grep "\\#define DRIVERVERSION" include/rtw_version.h | awk '{print $$3}' | tr -d v\\")

if not, it will return error in Raspbian:
Makefile:1085: *** unterminated call to function 'shell': missing ')'.  Stop

**Comment by jadentheprogrammer06** [comment]
Thanks! This helped me on Pop OS / Ubuntu.

**Comment by stu2005** [comment]
#209

**Comment by RICCIARDI-Adrien** [comment]
Hi,
this issue is fixed by commit bca492d6933bf2ba7fd20423f25a424ad5559fb2, I think it can be closed.
