### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by slythno** [gnab/rtl8812au#232]
make ARCH=armv8l CROSS_COMPILE= -C /lib/modules/4.19.95-perf-gfed612a/build M=/data/data/com.termux/files/home/rtl8812au  modules
make[1]: *** /lib/modules/4.19.95-perf-gfed612a/build: No such file or directory.  Stop.
make: *** [Makefile:1086: modules] Error 2

**Comment by Moxin1044** [comment]
How is this problem solved?
