### ISSUE TITLE
Breaks for kernel version 4.6

### ISSUE THREAD

**Issue by spwhitton** [gnab/rtl8812au#90]
My device can no longer connect with this new kernel version.  It would be great if you could update the driver.  Thanks!

**Comment by zebulon2** [comment]
Same problem here on an Arch 64 installation. Actually, the driver was working up to 4.6.3, but is broken with 4.6.4. It compiles, but it times out when trying to connect.

**Comment by intdel** [comment]
I am using it with 4.7. Works just fine for me.

**Comment by spwhitton** [comment]
Fails with 4.7.0-rc7 here.

**Comment by intdel** [comment]
Do you have any error messages or something? Btw. 4.7 is out maybe they fixed a bug, so try it with that. Also make sure wifi is actually enabled in your kernel config.

**Comment by spwhitton** [comment]
Good point.  When 4.7 reaches Debian experimental I'll try it out.

No errors in dmesg.  I just don't see an interface.

**Comment by zebulon2** [comment]
Just tried again with success. I do not know what happened, kernel name is still 4.6.4 (-1 on Arch 64). Possibly a dkms issue.

**Comment by spwhitton** [comment]
Now working on 4.8.  I think that the issue was with dkms, rather than this module.  Thanks for the feedback.
